server:
  port: ${USERSERVICE_PORT}
spring:
  application:
    name: auth-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXP_MS}
resend:
  apikey: ${RESEND_API_KEY}

eureka:
  client:
    enabled: false