server:
  port: ${APIGATEWAY_PORT:8080}

spring:
  application:
    name: apigateway-service
    web-application-type: reactive
  data:
    redis:
      url: ${REDIS_URL}
      # host: ${REDIS_HOST}
      # port: ${REDIS_PORT}
      # password: ${REDIS_PASSWORD}
      # connect-timeout: 2000ms
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**,
          filters:
            - PrefixPath=/api
            
        - id: order-service
          uri: ${ORDER_SERVICE_URL}
          predicates:
            - Path=/cart/**, /order/**
          filters:
            - AuthenticationFilter
            - PrefixPath=/api

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL}
          predicates:
            - Path=/products/**
          filters:
            - AuthenticationFilter
            - PrefixPath=/api
        
        - id: paymeny-service
          uri: ${PAYMENT_SERVICE_URL}
          predicates:
            - Path=/payments/**
          filters:
            - AuthenticationFilter
            - PrefixPath=/api
        
        - id: users-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
            - PrefixPath=/api

        - id: file-service
          uri: ${FILE_SERVICE_URL}
          predicates:
            - Path=/file/**
          filters:
            - AuthenticationFilter
            - PrefixPath=/api

logging:
  level:
    com.growthsheet.apigateway_service: INFO
    org.springframework.cloud.gateway: INFO

eureka:
  client:
    enabled: false
